name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install jq and Read Config
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
    
        # Captura as variáveis do arquivo JSON
        SERVICE_NAME=$(jq -r .service.name configs/develop.json)
        PUBLISHED_PORT=$(jq -r .service.published_port configs/develop.json)
        TARGET_PORT=$(jq -r .service.target_port configs/develop.json)
        REPLICAS=$(jq -r .service.replicas configs/develop.json)
    
        # Verifica se as variáveis estão definidas corretamente
        echo "SERVICE_NAME: $SERVICE_NAME"
        echo "PUBLISHED_PORT: $PUBLISHED_PORT"
        echo "TARGET_PORT: $TARGET_PORT"
        echo "REPLICAS: $REPLICAS"
    
        # Se alguma variável estiver vazia, falha imediatamente
        if [[ -z "$SERVICE_NAME" || -z "$PUBLISHED_PORT" || -z "$TARGET_PORT" || -z "$REPLICAS" ]]; then
          echo "Erro: Uma ou mais variáveis estão vazias."
          exit 1
        fi
    
        # Exporta as variáveis para o ambiente do GitHub Actions
        echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
        echo "PUBLISHED_PORT=$PUBLISHED_PORT" >> $GITHUB_ENV
        echo "TARGET_PORT=$TARGET_PORT" >> $GITHUB_ENV
        echo "REPLICAS=$REPLICAS" >> $GITHUB_ENV

    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest
        push: true
        file: ./Dockerfile
        context: .

    - name: Deploy to Docker Swarm
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Verifica se o serviço existe
          if docker service ls | grep -q ${{ env.SERVICE_NAME }}; then
            echo "Service exists, updating image, ports, and replicas..."
    
            if [[ -n "${{ env.PUBLISHED_PORT }}" && -n "${{ env.TARGET_PORT }}" && -n "${{ env.REPLICAS }}" ]]; then
              docker service update \
                --image ${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest \
                --publish-rm published=${{ env.PUBLISHED_PORT }},target=${{ env.TARGET_PORT }} \
                --publish-add published=${{ env.PUBLISHED_PORT }},target=${{ env.TARGET_PORT }} \
                --replicas ${{ env.REPLICAS }} \
                ${{ env.SERVICE_NAME }}
            else
              echo "Erro: Portas ou réplicas não definidas."
              exit 1
            fi
          fi
